# Generated by Django 2.2 on 2020-02-08 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_getter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedata',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipedata',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None),
        ),
        migrations.AddField(
            model_name='recipedata',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
