# Generated by Django 2.2 on 2020-02-09 12:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_getter', '0002_auto_20200208_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedata',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
