# Generated by Django 2.2 on 2020-02-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_getter', '0003_auto_20200209_1239'),
        ('recipe_getter', '0003_auto_20200210_2137'),
    ]

    operations = [
    ]
