# Generated by Django 2.2 on 2020-02-21 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_getter', '0004_merge_20200220_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedata',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipedata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
