# Generated by Django 2.2.13 on 2020-06-11 21:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_getter', '0005_auto_20200221_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='recipedata',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipedata',
            name='meal_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='recipedata',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), default=list, size=None),
        ),
    ]
