# Generated by Django 2.2.13 on 2020-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_getter', '0006_auto_20200611_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
